name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: "🚀 Features"
    labels:
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
  - title: "📝 Documentation"
    labels:
      - "docs"

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No significant changes.'