name-template: 'v$NEXT_MAJOR_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION'
prerelease: true
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug fixes'
    labels: ['fix', 'bug']
  - title: '📖 Docs'
    labels: ['docs']
  - title: '🧰 Misc'
    labels: ['chore', 'CI']
change-template: '- #$NUMBER: $TITLE'
template: |
  ## Changes
  $CHANGES